### ISSUE TITLE
No data transferred from serial gadget to host

### ISSUE THREAD

**Issue by gothaf** [folkien/pyIoCat#1]
Hi, I was trying this tool and I encountered a problem. My setup is as follows: a PC running Ubuntu 18.04 and a Raspberry Pi Zero running Raspbian, set up as a serial gadget. I have configured and tested the serial port on both host and target device writing and reading text lines back and forth. I have set up serialCat on both devices also. When I try to send a file from PC to RPi everything works as it should. The same thing from the RPi to the PC  results in the following error

`pi@raspberry:~/pyIoCat $ serialCat -i test.txt -o log.txt -d /dev/ttyGS0`
`Port  /dev/ttyGS0  opened.`
`Output to  log.txt .`
`Input from  test.txt .`
`InputSize :  48 Bytes.`
`Transmitted 0/48B. Readed 0/48B. Delta = 0B.`  
`No data time 1.00548505783 s.`
`Transmitted 0/48B. Readed 0/48B. Delta = 0B.`  
`No data time 2.00934410095 s.`
`Transmitted 0/48B. Readed 0/48B. Delta = 0B.`  
`Whole read transfer time: 2.01 s.`
`Transfer speed: 0.0 kB/s.`
`Baudrate theoreticaly transfer speed: 10.0 kB/s.`
`Traceback (most recent call last):`
`  File "/usr/bin/serialCat", line 178, in <module>`
`    main()`
`  File "/usr/bin/serialCat", line 160, in main`
`    writeSize       = portHandle.write(chunk)`
`  File "/home/pi/.local/lib/python2.7/site-packages/serial/serialposix.py", line 552, in write`
`    raise writeTimeoutError`
`serial.serialutil.SerialTimeoutException: Write timeout`

and nothing is transferred. I use parity NONE on the RPi. Any idea why is this happening? Thanks!

**Comment by folkien** [comment]
SerialCat opens tty port with this settings
```python
# Serial port read
portHandle = serial.Serial(
    port=args.device,
    baudrate=defaultBaudrate,
    rtscts=True,
    parity=defaultParity,
    stopbits=serial.STOPBITS_ONE,
    bytesize=serial.EIGHTBITS,
    timeout=1,
    write_timeout=10
)
```

So it uses RTSCTS default and  there is write timeout 10s. In your log it looks like write timeout happend. Port was opened sucessfully  but maybe RPi(transmission PC->RPi) oraz PC(transmission RPi -> PC) raised up RTS flag which normally blocks transmission. You can try with `rtscts=False`. I can also add in newer program version option to enable/disable rtscts handling.

**Comment by folkien** [comment]
> SerialCat opens tty port with this settings
> 
> ```python
> # Serial port read
> portHandle = serial.Serial(
>     port=args.device,
>     baudrate=defaultBaudrate,
>     rtscts=True,
>     parity=defaultParity,
>     stopbits=serial.STOPBITS_ONE,
>     bytesize=serial.EIGHTBITS,
>     timeout=1,
>     write_timeout=10
> )
> ```
> 
> So it uses RTSCTS default and there is write timeout 10s. In your log it looks like write timeout happend. Port was opened sucessfully but maybe RPi raised up RTS flag which normally blocks transmission. You can try with `rtscts=False`. I can also add in newer program version option to enable/disable rtscts handling.

**Comment by gothaf** [comment]
Changing the rtscts to 'false' worked! But then, changing the rtscts back to 'true' also worked. So, now I am a little bit confused, but at least it works. Thank you!

**Comment by folkien** [comment]
I newest master version you can use
```shell
-F FLOWCONTROL, --flowcontrol FLOWCONTROL
                        Flowcontrol <none | rtscts >
```
